---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-grpc
  template:
    metadata:
      labels:
        app: server-grpc
    spec:
      containers:
        - name: server-grpc
          image: guanw0826/kubernetes-service-discovery-grpc-server:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service # Type of kubernetes resource
metadata:
  name: server-grpc-svc # Unique name of the resource
spec:
  selector:
    app: server-grpc
  type: NodePort # Expose the Pods by opening a port on each Node and proxying it to the service.
  ports: # Take incoming HTTP requests on port 8081 and forward them to the targetPort of 8081
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: grpc
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: server-grpc-svc-ingress
# spec:
#   rules:
#     - grpc:
#         paths:
#           - path: /
#             backend:
#               serviceName: server-grpc-svc
#               servicePort: 8082
